### ISSUE TITLE
Cannot read host file (home directory) on Ubuntu 22.04

### ISSUE THREAD

**Issue by PaperNick** [popey/spek-snap#2]
Hey, thanks a lot for packaging this app!

I tried running it on Ubuntu 22.04 and it works great. The only problem is that I cannot access any of my local files. I get "Permission denied" when opening a file.

I'm not familiar with snap packaging and not sure what needs to be changed in the yaml files to give the necessary permissions.

**Edit:** The folders in my home directory are symlinks to directories in another HDD.

**Comment by popey** [comment]
If you run `snap connect spek:removable-media` does that make the files accessible?

**Comment by PaperNick** [comment]
I solved the permission issues by manually adding the `removable-media` interface through the command-line:
```
snap connect spek:removable-media :removable-media
```

Now `snap connections spek` should return:
```
removable-media         spek:removable-media  :removable-media                  manual
```

**Edit:** Looks like we commented at the same time. Thanks for the assistance nevertheless :pray:
